#!/usr/bin/env python3
"""
尚硅谷电商数仓6.0 - 文档自动加工工具
将docx笔记转换为结构化学习材料
"""

import json
import os
import sys
from docx import Document
from datetime import datetime

# 文档配置
DOCS_CONFIG = [
    {
        "num": 2,
        "name": "尚硅谷大数据项目之电商数仓（2用户行为数据仓库）.docx",
        "short_name": "用户行为数据仓库",
        "video_range": "066-109",
        "difficulty": "⭐⭐⭐⭐",
        "duration": "4-5小时"
    },
    {
        "num": 3,
        "name": "尚硅谷大数据项目之电商数仓（3系统业务数据仓库）.docx",
        "short_name": "系统业务数据仓库",
        "video_range": "110-154",
        "difficulty": "⭐⭐⭐⭐",
        "duration": "4-5小时"
    },
    {
        "num": 4,
        "name": "尚硅谷大数据项目之电商数仓（4即席查询数据仓库）.docx",
        "short_name": "即席查询数据仓库",
        "video_range": "155-193",
        "difficulty": "⭐⭐⭐⭐⭐",
        "duration": "5-6小时"
    },
    {
        "num": 5,
        "name": "尚硅谷大数据项目之电商数仓（5CDH版数仓采集）.docx",
        "short_name": "CDH版数仓采集",
        "video_range": "赠送课程",
        "difficulty": "⭐⭐⭐",
        "duration": "3-4小时"
    }
]

def extract_docx_content(doc_path):
    """提取docx文档内容"""
    doc = Document(doc_path)
    
    content = []
    current_section = {"title": "", "content": []}
    
    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue
        
        # 检测章节标题
        if (text.startswith("第") and ("章" in text or "节" in text)) or \
           (text.startswith("第") and "模块" in text) or \
           text.startswith("一、") or text.startswith("二、") or \
           text.startswith("1.") or text.startswith("2."):
            if current_section["content"]:
                content.append(current_section)
            current_section = {"title": text, "content": []}
        else:
            current_section["content"].append(text)
    
    if current_section["content"]:
        content.append(current_section)
    
    return content

def generate_lesson_template(doc_info, sections):
    """生成学习材料模板"""
    
    template = f"""# 尚硅谷电商数仓6.0 - 模块{doc_info['num']}：{doc_info['short_name']}

> **对应视频**: {doc_info['video_range']}集  
> **原始文档**: {doc_info['name']}  
> **生成时间**: {datetime.now().strftime('%Y-%m-%d')}  
> **难度评级**: {doc_info['difficulty']}  
> **建议学习时长**: {doc_info['duration']}

---

## 🎯 课程开场（2分钟速览）

本模块是电商数仓项目的**第{doc_info['num']}阶段**，解决的核心问题是：【待补充】

**你将学到**:
- 【待从内容中提取关键知识点】

**面试高频考点**: 【待总结】

---

## 📚 核心知识点详解

### 1. 章节概览

本文档共包含 {len(sections)} 个主要章节：

"""
    
    # 添加章节列表
    for i, sec in enumerate(sections[:20], 1):
        title = sec['title'][:50] if sec['title'] else f"章节{i}"
        content_preview = sec['content'][0][:80] if sec['content'] else ""
        template += f"### {i}. {title}\n\n"
        if content_preview:
            template += f"> 预览: {content_preview}...\n\n"
    
    if len(sections) > 20:
        template += f"\n... 还有 {len(sections)-20} 个章节\n"
    
    template += """
---

## 📋 原始内容节选

以下是从原文档提取的关键内容，需要进一步整理加工：

"""
    
    # 添加每个章节的内容摘要
    for i, sec in enumerate(sections[:10], 1):
        if sec['title']:
            template += f"\n### {sec['title']}\n\n"
        
        # 取前5条非空内容作为预览
        preview_count = 0
        for line in sec['content']:
            if line.strip() and len(line) > 10:
                template += f"- {line[:150]}\n"
                preview_count += 1
                if preview_count >= 5:
                    break
        
        if len(sec['content']) > 5:
            template += f"- ... 还有 {len(sec['content'])-5} 条内容\n"
    
    template += """
---

## ⚠️ 注意

本文档是自动生成的初稿，需要人工进一步加工：
1. 提炼核心知识点
2. 添加代码示例
3. 设计自测题目
4. 补充面试要点
5. 完善学习建议

---

*Generated by OpenClaw Doc Processor*
"""
    
    return template

def process_single_doc(doc_config, base_path, output_path):
    """处理单个文档"""
    doc_path = os.path.join(base_path, "vito-6.0-materials/1.笔记", doc_config['name'])
    
    print(f"\n{'='*60}")
    print(f"Processing: {doc_config['name']}")
    print(f"{'='*60}")
    
    if not os.path.exists(doc_path):
        print(f"❌ File not found: {doc_path}")
        return False
    
    file_size = os.path.getsize(doc_path) / 1024 / 1024
    print(f"File size: {file_size:.1f} MB")
    
    try:
        # 提取内容
        print("Extracting content...")
        sections = extract_docx_content(doc_path)
        print(f"Found {len(sections)} sections")
        
        # 生成学习材料
        print("Generating lesson material...")
        lesson_content = generate_lesson_template(doc_config, sections)
        
        # 保存
        output_file = os.path.join(output_path, f"doc{doc_config['num']}_{doc_config['short_name']}.md")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(lesson_content)
        
        print(f"✅ Saved to: {output_file}")
        
        # 同时保存原始提取的JSON
        raw_data = {
            "doc_name": doc_config['short_name'],
            "total_sections": len(sections),
            "sections": sections
        }
        json_file = os.path.join(output_path, f"doc{doc_config['num']}_raw_extract.json")
        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(raw_data, f, ensure_ascii=False, indent=2)
        
        return True
        
    except Exception as e:
        print(f"❌ Error processing {doc_config['name']}: {str(e)}")
        import traceback
        traceback.print_exc()
        return False

def update_progress(progress_file, doc_num, status, output=None):
    """更新进度文件"""
    try:
        with open(progress_file, 'r', encoding='utf-8') as f:
            progress = json.load(f)
        
        idx = doc_num - 1
        progress['docs'][idx]['status'] = status
        progress['last_update'] = datetime.now().isoformat()
        
        if output:
            progress['docs'][idx]['output'] = output
        
        if status == 'completed':
            progress['docs'][idx]['progress'] = 100
        elif status == 'processing':
            progress['docs'][idx]['progress'] = 50
        
        with open(progress_file, 'w', encoding='utf-8') as f:
            json.dump(progress, f, indent=2)
            
    except Exception as e:
        print(f"Warning: Could not update progress: {e}")

def main():
    # 路径配置
    workspace = "/home/admin/.openclaw/workspace"
    base_path = os.path.join(workspace, "learning_materials")
    output_path = os.path.join(base_path, "processed_lessons")
    progress_file = os.path.join(base_path, "process_progress.json")
    
    print("="*60)
    print("OpenClaw Doc Processor - 尚硅谷电商数仓6.0")
    print("="*60)
    print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Output directory: {output_path}")
    
    # 确保输出目录存在
    os.makedirs(output_path, exist_ok=True)
    
    # 处理剩余的4个文档
    for doc_config in DOCS_CONFIG:
        doc_num = doc_config['num']
        
        # 更新进度为处理中
        update_progress(progress_file, doc_num, 'processing')
        
        # 处理文档
        success = process_single_doc(doc_config, base_path, output_path)
        
        # 更新进度
        if success:
            output_file = f"processed_lessons/doc{doc_num}_{doc_config['short_name']}.md"
            update_progress(progress_file, doc_num, 'completed', output_file)
            print(f"✅ Document {doc_num} completed")
        else:
            update_progress(progress_file, doc_num, 'failed')
            print(f"❌ Document {doc_num} failed")
    
    # 更新总体状态
    try:
        with open(progress_file, 'r', encoding='utf-8') as f:
            progress = json.load(f)
        
        progress['status'] = 'completed'
        progress['end_time'] = datetime.now().isoformat()
        
        with open(progress_file, 'w', encoding='utf-8') as f:
            json.dump(progress, f, indent=2)
    except Exception as e:
        print(f"Warning: Could not finalize progress: {e}")
    
    print("\n" + "="*60)
    print("All documents processed!")
    print(f"End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)

if __name__ == "__main__":
    main()
